% This program runs Flow800 using the data.dat in this folder.
% 2016-10-19
% Jean-Sebastien Dick
clear all;
close all;
clc

%% Simulations vitesse

% Variables de remplissages et de modes circonférentiels
fill = [100];
E = 69000000000;
nu = 0.3;
rho = 2700;
L = 2;
t = 0.00075;

U_bar = 6.5;
vitesse = U_bar*pi^2/L*sqrt(E*t^2/(12*rho*(1-nu^2)));
% Create INPUT
for k = 1:1
    for n = 2:4
        titre = ['PROJET3_VITESSE_INTERNE', '_N', num2str(n)];
        
        FID = fopen([titre '.dat'], 'w');
        
        % Print
        fprintf(FID, '***                           DATA - FLOW80                                ***\n');
        fprintf(FID, '*** NE PAS DETRUIRE LES LIGNE DE CE FICHIER DEBUTANT AVEC DE ''*''           ***\n');
        fprintf(FID, '*** LORSQUE IBC =0, LES DEUX LIGNES /NODRES/ ET NP&NDIRECT/ _DOIVENT_      ***\n');
        fprintf(FID, '*** APPARAITRE MEME SI ELLES NE SONT PAS CONSIDEREES LORS DE L EXECUTION   ***\n');
        fprintf(FID, '*** FORMATS UTILISES: f1 = I2,1X , f2 = E12.6,1X                           ***\n');
        fprintf(FID, '******************************************************************************\n');
        fprintf(FID, 'ITITRE - 100A1              = %s\n', titre);
        fprintf(FID, 'NSET,IFREQ - 2f1            = 1  1\n');
        fprintf(FID, 'IPRINT,IFLUID,NSPEED - 3f1  = 0  0  1\n');
        fprintf(FID, 'RHOL,RHOR,NHA - 2f2,I2      =0.100000E+04 0.000000E+00 1\n');
        fprintf(FID, 'NOHARM(I),I=1,NHA - 10f1    =%d\n', n);
        fprintf(FID, 'NELEMS,NFREQ,IBC,N2 - 4f1   =24  2  1  1\n');
        fprintf(FID, 'NSE(I),I=1,N2 - 25f1        =1\n');
        fprintf(FID, 'NODRES - I2                 =4\n');
        fprintf(FID, 'NP&NDIRCT,I=1,NODRES - 16f1 =1  1  1  2  1  3  1  4\n');
        fprintf(FID, 'NGROUP - I2                 =1\n');
        fprintf(FID, 'N1 - I2                     =1\n');
        fprintf(FID, 'E(I),I=1,N1 - 25f2          =6.900000E+10\n');
        fprintf(FID, 'NU(I),I=1,N1 - 25f2         =0.300000E+00\n');
        fprintf(FID, 'RA(I),I=1,N1 - 25f2         =0.304800E+00\n');
        fprintf(FID, 'TH(I),I=1,N1 - 25f2         =0.750000E-03\n');
        fprintf(FID, 'RHO(I),I=1,N1 - 25f2        =0.270000E+04\n');
        fprintf(FID, 'LE(I),I=1,N1 - 25f2         =0.833333E-01\n');
        fprintf(FID, 'ICOUCH - I2                 = 0\n');
        fprintf(FID, '*** SI ICOUCH .NE. 0 ENTRER LES N1 MATRICES D''ELASTICITER  P(6,6) ENTRE    ***\n');
        fprintf(FID, '*** LES DEUX LIGNES TIRETEES CI-APRES DANS L''ORDRE  DE NUMEROTATION DES    ***\n');
        fprintf(FID, '***    NEOUDS -6F2 CHAQUE LIGNE *N.B :AUCUNE LIGNE VIDE LES MATRICES       ***\n');
        fprintf(FID, '***------------------------------------------------------------------------***\n');
        fprintf(FID, '***------------------------------------------------------------------------***\n');
        fprintf(FID, '*** NSPEED FOIS LE GROUPE DE CARTES CI-APRES (SI RHOL .NE. 0)              ***\n');
        fprintf(FID, '*** |   SI IUNIF=0, UNE SEULE CARTE /ROIN,ROEX,VITIN,VITEX/ NECESSAIRE     ***\n');
        fprintf(FID, '*** |   SI IUNIF=1, NELEMS CARTES /ROIN,ROEX,VITIN,VITEX/ NECESSAIRES      ***\n');
        fprintf(FID, '#### CAS DE PRESSION INTERNE OU FORCE AXIALE                               ###\n');
        fprintf(FID, 'PRESM,PRESX                 =0.000000E+00 0.000000E+00\n');
        fprintf(FID, '#### CAS D''ÉCOULEMENT SUPERSONIC COMPRESSIBLE/POTENTIEL ET PARTIEL. REMPLI ###\n');
        fprintf(FID, 'COMP,MACH,SOUND,PRESSURE-   =00 0.00 0000.00 0.000000E+00\n');
        fprintf(FID, 'IUNIF - I2                  = 1\n');
        fprintf(FID, 'ROIN,ROEX,VITIN,VITEX - 4f2 =0.100000E+04 0.000000E+00 %.6E 0.000000E+00\n', vitesse);
        for i = 2:24
            fprintf(FID, '                             0.100000E+04 0.000000E+00 %.6E 0.000000E+00\n', vitesse);
        end
        fprintf(FID, '### CAS D''UNE COUCHE LIMITE TURBULENTE                                     ###\n');
        fprintf(FID, 'SA SB SC SD SK1 SK2         =0.000000E+00 0.000000E+00 0.000000E+00 0.000000E+00 0.000000E-00 0.000000E-00\n');
        fprintf(FID, 'IDAM IDENT                  =0  0\n');
        fprintf(FID, 'VITESSE UCLI=1, NNODE       =0.000000E+00 0.000000E+00 0.000000E+00 0.000000E+00 0.000000E+00 0.000000E+02\n');
        fprintf(FID, 'IN JN KF KN                 =0    0    0    0\n');
        fprintf(FID, 'ZETA(I) OU C(I)             =0.000000E-00');
        
        fclose(FID);
        
        % RENAME INPUT
        movefile(([titre '.dat']),'data.dat')
        
        % Run flow 800
        
        % This line calls the program flow800
        % It returns the status 0 if it is completed succesfully
        % Ir returns the status 1 if it wasn't
        % cmdout contains the data generated by the program
        % Create the directory where flow800.exe is copied with those lines
        % windows key + r, cmd, enter
        % dos('j:\batch\flow80.bat')
        % dos('z:\flow80')
        [status,cmdout] = dos('flow800') ;
        disp(status)
        disp(cmdout)
        
        movefile('data.dat',([titre '.dat']))
        
        % Open and rename OUTPUT
        % Opens in reading mode the Output FIle
        fileID = fopen('OUTPUT.dat','r');
        tline = fgets(fileID) ;
        while ischar(tline)
            
            %Finds the line containing the number of the harmonic
            if any(strfind(tline,'NOHARM(I)'),1)
                disp(tline)
                found = tline ;
                ii = 0 ;
                % Separates the line in strings
                tempcell = strread(found, '%s', 'delimiter','=') ;
                out.noharm = tempcell{end}(1) ;
            end
            
%             if any(strfind(tline,'NO.          OMEGA          RAD./SEC.      HERTZ'),1)
%                 tline = fgets(fid);
%                 tline = fgets(fid);
%                 C_data = textscan(fileID,,'%d %f %f %f');
%                 C_data(1);
%             end
            
            tline = fgets(fileID);
        end
        
        
        %Rename the output file:
        %Indicate the number of the harmonic
        disp(out.noharm)
        disp(n)
        num = [num2str(n) '.dat'] ;
        % The following variable is used for renaming the OUTPUT.dat file
        Fill = [num2str(fill(k)) 'fill'];
        
        % Get all  files in the current folder finishing with .dat
        files = dir('*.dat');
        d = [pwd  '\'];
        % Loop through each files found
        for id = 1:length(files)
            % Get the file name (minus the extension)
            [~, f] = fileparts(files(id).name);
            if strcmp(f,'OUTPUT')
                oldname = [d f '.dat'] ;
                %movefile(sprintf(strcat(fill,'_n=%'), num),files(id).name);
                newname = sprintf(strcat('%s',Fill,'_n%s'),d, num);
                fclose(fileID);
                % DOS Command to copy and rename the file
                dos(['copy "' oldname '" "' newname '"']);
            end
        end
    end
end



%% Simulations liquide partiel
% Variables de remplissages et de modes circonférentiels
fill = [25,50,75,100];

% Create INPUT
for k = 1:4
    for n = 1:20
        titre = ['PROJET3_FILL', num2str(fill(k)), '_N', num2str(n)];
        
        FID = fopen([titre '.dat'], 'w');
        
        % Print
        fprintf(FID, '***                           DATA - FLOW80                                ***\n');
        fprintf(FID, '*** NE PAS DETRUIRE LES LIGNE DE CE FICHIER DEBUTANT AVEC DE ''*''           ***\n');
        fprintf(FID, '*** LORSQUE IBC =0, LES DEUX LIGNES /NODRES/ ET NP&NDIRECT/ _DOIVENT_      ***\n');
        fprintf(FID, '*** APPARAITRE MEME SI ELLES NE SONT PAS CONSIDEREES LORS DE L EXECUTION   ***\n');
        fprintf(FID, '*** FORMATS UTILISES: f1 = I2,1X , f2 = E12.6,1X                           ***\n');
        fprintf(FID, '******************************************************************************\n');
        fprintf(FID, 'ITITRE - 100A1              = %s\n', titre);
        fprintf(FID, 'NSET,IFREQ - 2f1            = 1  1\n');
        fprintf(FID, 'IPRINT,IFLUID,NSPEED - 3f1  = 0  0  1\n');
        fprintf(FID, 'RHOL,RHOR,NHA - 2f2,I2      =0.100000E+04 0.000000E+00 1\n');
        fprintf(FID, 'NOHARM(I),I=1,NHA - 10f1    =%d\n', n);
        fprintf(FID, 'NELEMS,NFREQ,IBC,N2 - 4f1   =24  2  1  1\n');
        fprintf(FID, 'NSE(I),I=1,N2 - 25f1        =1\n');
        fprintf(FID, 'NODRES - I2                 =4\n');
        fprintf(FID, 'NP&NDIRCT,I=1,NODRES - 16f1 =1  1  1  2  1  3  1  4\n');
        fprintf(FID, 'NGROUP - I2                 =1\n');
        fprintf(FID, 'N1 - I2                     =1\n');
        fprintf(FID, 'E(I),I=1,N1 - 25f2          =6.900000E+10\n');
        fprintf(FID, 'NU(I),I=1,N1 - 25f2         =0.300000E+00\n');
        fprintf(FID, 'RA(I),I=1,N1 - 25f2         =0.304800E+00\n');
        fprintf(FID, 'TH(I),I=1,N1 - 25f2         =0.750000E-03\n');
        fprintf(FID, 'RHO(I),I=1,N1 - 25f2        =0.270000E+04\n');
        fprintf(FID, 'LE(I),I=1,N1 - 25f2         =0.833333E-01\n');
        fprintf(FID, 'ICOUCH - I2                 = 0\n');
        fprintf(FID, '*** SI ICOUCH .NE. 0 ENTRER LES N1 MATRICES D''ELASTICITER  P(6,6) ENTRE    ***\n');
        fprintf(FID, '*** LES DEUX LIGNES TIRETEES CI-APRES DANS L''ORDRE  DE NUMEROTATION DES    ***\n');
        fprintf(FID, '***    NEOUDS -6F2 CHAQUE LIGNE *N.B :AUCUNE LIGNE VIDE LES MATRICES       ***\n');
        fprintf(FID, '***------------------------------------------------------------------------***\n');
        fprintf(FID, '***------------------------------------------------------------------------***\n');
        fprintf(FID, '*** NSPEED FOIS LE GROUPE DE CARTES CI-APRES (SI RHOL .NE. 0)              ***\n');
        fprintf(FID, '*** |   SI IUNIF=0, UNE SEULE CARTE /ROIN,ROEX,VITIN,VITEX/ NECESSAIRE     ***\n');
        fprintf(FID, '*** |   SI IUNIF=1, NELEMS CARTES /ROIN,ROEX,VITIN,VITEX/ NECESSAIRES      ***\n');
        fprintf(FID, '#### CAS DE PRESSION INTERNE OU FORCE AXIALE                               ###\n');
        fprintf(FID, 'PRESM,PRESX                 =0.000000E+00 0.000000E+00\n');
        fprintf(FID, '#### CAS D''ÉCOULEMENT SUPERSONIC COMPRESSIBLE/POTENTIEL ET PARTIEL. REMPLI ###\n');
        fprintf(FID, 'COMP,MACH,SOUND,PRESSURE-   =00 0.00 0000.00 0.000000E+00\n');
        fprintf(FID, 'IUNIF - I2                  = 1\n');
        fprintf(FID, 'ROIN,ROEX,VITIN,VITEX - 4f2 =0.100000E+04 0.000000E+00 0.000000E+00 0.000000E+00\n');
        for i = 2:24*fill(k)/100
            fprintf(FID, '                             0.100000E+04 0.000000E+00 0.000000E+00 0.000000E+00\n');
        end
        for j = i:23
            fprintf(FID, '                             0.000000E+00 0.000000E+00 0.000000E+00 0.000000E+00\n');
        end
        fprintf(FID, '### CAS D''UNE COUCHE LIMITE TURBULENTE                                     ###\n');
        fprintf(FID, 'SA SB SC SD SK1 SK2         =0.000000E+00 0.000000E+00 0.000000E+00 0.000000E+00 0.000000E-00 0.000000E-00\n');
        fprintf(FID, 'IDAM IDENT                  =0  0\n');
        fprintf(FID, 'VITESSE UCLI=1, NNODE       =0.000000E+00 0.000000E+00 0.000000E+00 0.000000E+00 0.000000E+00 0.000000E+02\n');
        fprintf(FID, 'IN JN KF KN                 =0    0    0    0\n');
        fprintf(FID, 'ZETA(I) OU C(I)             =0.000000E-00');
        
        fclose(FID);
        
        % RENAME INPUT
        movefile(([titre '.dat']),'data.dat')
        
        % Run flow 800
        
        % This line calls the program flow800
        % It returns the status 0 if it is completed succesfully
        % Ir returns the status 1 if it wasn't
        % cmdout contains the data generated by the program
        % Create the directory where flow800.exe is copied with those lines
        % windows key + r, cmd, enter
        % dos('j:\batch\flow80.bat')
        % dos('z:\flow80')
        [status,cmdout] = dos('flow800') ;
        disp(status)
        disp(cmdout)
        
        movefile('data.dat',([titre '.dat']))
        
        % Open and rename OUTPUT
        % Opens in reading mode the Output FIle
        fileID = fopen('OUTPUT.dat','r');
        tline = fgets(fileID) ;
        while ischar(tline)
            
            %Finds the line containing the number of the harmonic
            if any(strfind(tline,'NOHARM(I)'),1)
                disp(tline)
                found = tline ;
                ii = 0 ;
                % Separates the line in strings
                tempcell = strread(found, '%s', 'delimiter','=') ;
                out.noharm = tempcell{end}(1) ;
            end
            
%             if any(strfind(tline,'NO.          OMEGA          RAD./SEC.      HERTZ'),1)
%                 tline = fgets(fid);
%                 tline = fgets(fid);
%                 C_data = textscan(fileID,,'%d %f %f %f');
%                 C_data(1);
%             end
            
            tline = fgets(fileID);
        end
        
        
        %Rename the output file:
        %Indicate the number of the harmonic
        disp(out.noharm)
        disp(n)
        num = [num2str(n) '.dat'] ;
        % The following variable is used for renaming the OUTPUT.dat file
        Fill = [num2str(fill(k)) 'fill'];
        
        % Get all  files in the current folder finishing with .dat
        files = dir('*.dat');
        d = [pwd  '\'];
        % Loop through each files found
        for id = 1:length(files)
            % Get the file name (minus the extension)
            [~, f] = fileparts(files(id).name);
            if strcmp(f,'OUTPUT')
                oldname = [d f '.dat'] ;
                %movefile(sprintf(strcat(fill,'_n=%'), num),files(id).name);
                newname = sprintf(strcat('%s',Fill,'_n%s'),d, num);
                fclose(fileID);
                % DOS Command to copy and rename the file
                dos(['copy "' oldname '" "' newname '"']);
            end
        end
    end
end

%% Post-Processing





